# Generated by Django 6.1.1 on 2026-09-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='debug_field',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
