# Generated by Django 6.1.1 on 2026-09-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_debug_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='debug_field',
        ),
    ]
