# Generated by Django 6.1.1 on 2026-09-22 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_department_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department_fk',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department'),
        ),
    ]
