# Generated by Django 6.1.1 on 2026-09-22 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_remove_employee_department_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=5)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='employee_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='employees.employee')),
            ],
        ),
    ]
